//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnWebEntities2 : DbContext
    {
        public DoAnWebEntities2()
            : base("name=DoAnWebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHoaDonKH> CTHoaDon { get; set; }
        public virtual DbSet<HoaDonKH> HoaDon { get; set; }
        public virtual DbSet<HoiÐapKH> HoiÐap { get; set; }
        public virtual DbSet<LoaiTaiKhoanKH> LoaiTaiKhoan { get; set; }
        public virtual DbSet<MauSacKH> MauSac { get; set; }
        public virtual DbSet<NhaSanXuatKH> NhaSanXuat { get; set; }
        public virtual DbSet<SanPhamKH> SanPham { get; set; }
        public virtual DbSet<TaiKhoanKH> TaiKhoan { get; set; }
    }
}
