//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DoAnWebEntities : DbContext
    {
        public DoAnWebEntities()
            : base("name=DoAnWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoiÐap> HoiÐap { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<MauSac> MauSacs { get; set; }
        public virtual DbSet<NhaSanXuat> NhaSanXuats { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual ObjectResult<TimKiemSP_Result> TimKiemSP(string loaiSP, string tenSP, string nSX, Nullable<int> giaMin, Nullable<int> giaMax)
        {
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var nSXParameter = nSX != null ?
                new ObjectParameter("NSX", nSX) :
                new ObjectParameter("NSX", typeof(string));
    
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(int));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemSP_Result>("TimKiemSP", loaiSPParameter, tenSPParameter, nSXParameter, giaMinParameter, giaMaxParameter);
        }
    }
}
